### ISSUE TITLE
Wish to download test_conf.json used at plugfest

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Test-Framework#2]
I am still confused about where to find the test_conf.json file with the sample tests used at plugfest.
I was told to look in the plugfest zip but where is that residing?

**Comment by billdodd** [comment]
The zip file was uploaded to the SPMF Tools Taskforce documents area. It's the most recent file in that folder.

**Comment by jbobzin-insyde** [comment]
found it. thanks.
