### ISSUE TITLE
No such file or directory: results.json

### ISSUE THREAD

**Issue by maximyep** [DMTF/Redfish-Test-Framework#8]
simple test execution (according to the wiki) throws an error:

Running tests... 
----------------------------------------------------------------------
 test_Other_Tests_Redfish_Mockup_Creator_master (__main__.RedfishTestCase) ... WARNING:root:OSError opening JSON results from file results.json in directory /home/max/redfish/Redfish-Test-Framework/Other-Tests/Redfish-Mockup-Creator-master/output-2019-02-19T123022Z, error: [Errno 2] No such file or directory: '/home/max/redfish/Redfish-Test-Framework/Other-Tests/Redfish-Mockup-Creator-master/output-2019-02-19T123022Z/results.json'

**Comment by billdodd** [comment]
Some of the individual Redfish test tools create a `results.json` file that summarizes the results of the run. But many of the tools do not. The Redfish-Test-Framework script looks for that file in a particular location for each of the tests run. If it is found for a test, it includes it in the overall results report. If it is not found the report for that test indicates success/failure based on the return code of the test tool (zero for success, non-zero for failure). And a warning noting that the results.json file was not found is logged. 

The Redfish-Mockup-Creator is one of the tools that does not create a `results.json` file. So the warning message you are seeing is expected.

Perhaps the warning message can be modified to look less like an error to avoid confusion.
